[project]
name = "langdoc-ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pdf2image>=1.17.0",
    "pytesseract>=0.3.13",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "ruff>=0.9.6",
]
